CREATE TABLE LcTask (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    parentId BIGINT,
    name VARCHAR(255),
    description VARCHAR(255),
    actualStartTime BIGINT,
    actualEndTime BIGINT,
    planStartTime BIGINT,
    planEndTime BIGINT,
    priority INTEGER,
    remark VARCHAR(255),
    status VARCHAR(255),
    childStatus INTEGER,
    PRIMARY KEY (id));
create index indexParentId on LcTask(parentId);
create index indexActualStartTime on LcTask(actualStartTime);
create index indexPlanStartTime on LcTask(planStartTime);
create index indexStatus on LcTask(status);
create index indexChildStatus on LcTask(childStatus);

