server:
  port: 8086
spring:
  datasource:
    url: jdbc:derby:db/life-compass;create=true
    default-catalog: App
    username:
    password:
    driver-class-name: org.apache.derby.jdbc.EmbeddedDriver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      database-platform: org.hibernate.dialect.DerbyTenSevenDialect
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

